#!/bin/bash
IMAGE=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1).png
URL="i.techwolf12.nl"
mkdir -p /tmp/screenshots/
scrot -s /tmp/screenshots/$IMAGE
scp -B -p /tmp/screenshots/$IMAGE root@ns1.droiddev.nl:/var/www/i.techwolf12.nl/web/.
notify "Successfully uploaded" http://$URL/$IMAGE


echo -n http://$URL/$IMAGE | xclip -selection primary     &>/dev/null
echo -n http://$URL/$IMAGE | xclip -selection clipboard   &>/dev/null

