#!/bin/bash
###
# Issue a development certificate.
# Thanks to Angelo Geels for this script!
###

# Generate private key
openssl genrsa -out $HOME/certs/$1.key 4096
chmod 400 $HOME/certs/$1.key

# Create certificate request
openssl req -new -key $HOME/certs/$1.key -out $HOME/certs/$1.csr -subj "/C=NL/ST=Noord-Holland/L=Heerhugowaard/O=Techwolf12/CN=$1"
chmod 444 $HOME/certs/$1.csr

# Issue certificate
openssl x509 -req -in $HOME/certs/$1.csr -CA $DOTFILES/CA/Techwolf12.crt -CAkey $DOTFILES/secrets/Techwolf12CA.key -CAcreatserial -out $HOME/certs/$1.crt -days 712
chmod 444 $HOME/certs/$1.crt

echo
echo
echo " Certificate issued for 2 years"
echo

