#!/bin/bash

OLDWD=$PWD
cd $HOME/dotfiles
git pull

# Import gpg data (might be refreshed on other pc's)
#gpg --output - --decrypt secrets/gpg-pubkeyring.gpg | gpg --import
#gpg --output - --decrypt secrets/gpg-ownertrust.gpg | gpg --import-ownertrust

gpg --keyserver hkp://pool.sks-keyservers.net/ --refresh-keys

# Export the data again
gpg --export-ownertrust | gpg --batch --yes --output secrets/gpg-ownertrust.gpg --sign --encrypt
gpg -a --output /tmp/pubkeys.asc --export
gpg --batch --yes --output secrets/gpg-pubkeyring.gpg --sign --encrypt /tmp/pubkeys.asc
gpg -a --batch --yes --output gnupg/2F2546D8.asc --export 0x2F2546D8

# Upload the GnuPG key to techwolf12.nl
echo "cd web/keys\nput gnupg/2F2546D8.asc 2F2546D8.asc\nbye" | ftp ftp.droiddev.nl

# Password database
gpg --batch --yes --output secrets/pass.gpg --sign --encrypt secrets/keepass.kdb
# Java keystore
gpg --batch --yes --output secrets/android.gpg --sign --encrypt secrets/android.jks

cp $HOME/.mozilla/firefox/b6qhetnq.default/stylish.sqlite  misc/firefox.stylish/stylish.sqlite

git add secrets/gpg-pubkeyring.gpg secrets/gpg-ownertrust.gpg secrets/pass.gpg gnupg/2F2546D8.asc misc/firefox.stylish/stylish.sqlite secrets/android.gpg
git commit -m "Automatic dotupdate $(date +"%m-%d-%Y %r")"
git push


if [ -d /home/techwolf12/scripts ] ; then
    for file in /home/techwolf12/scripts/*; do
        sudo ln -sf $file /usr/bin/.;
    done
fi

cd $OLDWD
