#!/bin/bash
if ps ax | grep -v grep | grep 'i3lock'
then
    echo "i3 lock is already running"
else

if [ $1 -eq 1 ] ; then
    i3lock -b -t -i /home/techwolf12/Pictures/lock.png
else
    scrot /tmp/screenshot.png
    convert /tmp/screenshot.png -blur 0x5 /tmp/screenshotblur.png
    i3lock -b -t -i /tmp/screenshotblur.png
fi
fi

