#!/usr/bin/env python
"""
Author: Christiaan de Die le Clercq (@techwolf12) <contact@techwolf12.nl>
License: GPL v3 or later at your choice
"""
import notify2
import sys
import os

notify2.init("Tech's Notifier")

if len(sys.argv) <= 2 or len(sys.argv) > 4:
    n = notify2.Notification(raw_input(""), raw_input(""))
else:
    if sys.argv[1] == "f":
        with open(sys.argv[3], "r") as f:
            content = f.read()
        n = notify2.Notification(sys.argv[2], content)
    elif sys.argv[1] == "e":
        n = notify2.Notification(sys.argv[2], os.popen(sys.argv[3]).read().splitlines()[0])
    else:
        n = notify2.Notification(sys.argv[1], sys.argv[2])

print('Done')
n.show()

