#!/bin/zsh

# Aliases to not delete everything
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Programs
alias vlcplay='vlc -f --no-video-title-show --no-osd --play-and-exit -q'
alias sshproxy='ssh -Nn -D 1080'
alias gpge='gpg --armor --encrypt --sign'
alias gpgs='gpg --clearsign'
alias swebsrv='python -m SimpleHTTPServer 8000'
alias ytmp3='youtube-dl --extract-audio --audio-format mp3'

# Unclear stuff
alias please='sudo'
alias fucking='sudo'
alias down="please shutdown -h now"

# Stolen from Mirko (again yes)
# Kill current shell (Leaves no trace of commands.)
alias kcs="kill -9 $$"

# Get your outer IP address.
alias xip="curl icanhazip.com"

alias ix="curl -n -F 'f:1=<-' ix.io"
alias curl="curl -s -S"

alias openports="nmap portquiz.net"
alias mkdir='mkdir -pv'
alias df='df -H'
alias vir='vim -R'
alias intip="/sbin/ifconfig | grep 'inet addr:' | sed '/127.0.0.1/d' | cut -d: -f2 | awk '{ print $1}'"
alias cordova="phonegap cordova"
alias prettyjson="python -mjson.tool"
alias apt-get="sudo apt-get"
alias gpg="gpg2"
# Debian packaging
alias dquilt="quilt ­­quiltrc=${HOME}/.quiltrc­dpkg"
# Termart
alias pizza='curl -L http://git.io/pizzza'
alias pancakes='curl -L http://git.io/pancakes'
