#!/bin/zsh

# Aliases to not delete everything
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Programs
alias vlcplay='vlc -f --no-video-title-show --no-osd --play-and-exit -q'
alias sshproxy='ssh -Nn -D 1080'
alias gpgs='gpg --clearsign'
alias swebsrv='python -m SimpleHTTPServer 8000'
alias ytmp3='youtube-dl --extract-audio --audio-format mp3'
alias s='screen'
alias sl='sl -ae'
# Unclear stuff
alias please='sudo'
alias fucking='sudo'
alias down="please shutdown -h now"

# Stolen from Mirko (again yes)
# Kill current shell (Leaves no trace of commands.)
alias kcs="kill -9 $$"
alias xmerge="xrdb -merge $HOME/.Xresources"

# Get your outer IP address.
alias xip="curl icanhazip.com"

alias ix="curl -n -F 'f:1=<-' ix.io"
alias curl="curl -s -S"

alias openports="nmap portquiz.net"
alias mkdir='mkdir -pv'
alias df='df -H'
alias vir='vim -R'
alias intip="/sbin/ifconfig | grep 'inet addr:' | sed '/127.0.0.1/d' | cut -d: -f2 | awk '{ print $1}'"
alias prettyjson="python -mjson.tool"
alias apt-get="sudo apt-get"
alias gpg="gpg2"
alias c="clear"
alias bc="bc -q"
# Debian packaging
alias dquilt="quilt ­­quiltrc=${HOME}/.quiltrc­dpkg"
alias checkinstall="checkinstall --maintainer \"contact@techwolf12.nl\" --install=no"
# Termart
alias pizza='curl -L http://git.io/pizzza'
alias pancakes='curl -L http://git.io/pancakes'
alias weather='curl http://wttr.in/'

alias startkeylog='sudo logkeys --start --keymap $HOME/Programs/logkeys/keymaps/en_US_ubuntu_1204.map --output /tmp/keys.log'
alias stopkeylog='sudo logkeys -k'

# Radio stations
alias freshuk='echo "clear\nadd tunein:station:s222437\nplay 0\nclose" | nc localhost 6600'

# macOS specific stuff
alias finder="open . -a finder"
alias xcode="open . -a xcode"
alias astudio="open . -a \"Android Studio\""
