#!/bin/bash

# Aliases to not delete everything
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Custom git
alias gittime='git log -5 --format="%cd"'
alias gitl='git log --graph --abbrev-commit --pretty=oneline --decorate'
alias gitaddcommitpullpush='git add . && git commit -a && git pull && git push'
alias gitc='git commit -S'

# Programs
alias vlcplay='vlc -f --no-video-title-show --no-osd --play-and-exit -q'
alias socksstart='ssh -Nn -D 1080 techwolf12@ns1.droiddev.nl'
alias dtmfdecode='multimon | grep "DTMF\|CCIR\|AFSK"'
alias gpge='gpg --armor --encrypt --sign'
alias gpgs='gpg --clearsign'
alias irssi='ssh -t techwolf12@ns1.droiddev.nl "screen -x"'
