# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Path to your oh-my-zsh installation.
export ZSH=$HOME/dotfiles/zsh/oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="techwolf"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Which plugins would you like to load? 
plugins=(git debian common-aliases encode64 npm nyan wd)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH="/root/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export LANG=en_US.UTF-8

source $HOME/dotfiles/zsh/aliases

PATH=$PATH:$HOME/scripts

# Start GPG agent with SSH support
#if test -f $XDG_RUNTIME_DIR/gpg-agent-info && kill -0 $(head -n 1 $XDG_RUNTIME_DIR/gpg-agent-info | cut -d: -f2) 2>/dev/null ; then
#    eval $(< $XDG_RUNTIME_DIR/gpg-agent-info)
#else
#    eval $(gpg-agent --daemon --enable-ssh-support --write-env-file $XDG_RUNTIME_DIR/gpg-agent-info)
#fi
#export GPG_AGENT_INFO
#export SSH_AUTH_SOCK

# Run login script
$HOME/.loginscript



